#include "DATA_TYPES.h"
#include "LBIT_Math.h"
#include "TIMER_INTERFACE.h"
#include "MDIO_INTERFACE.h"
#include "TIMER_PRIVATE.h"
#define  F_CPU		16000000
#include "util/delay.h"	
int main(void)
{
	MDIO_SETPIN_STATUS(PORTD,PIN0,OUTPUT);
	MDIO_SETPIN_STATUS(PORTC,PIN7,OUTPUT);
	MDIO_SETPIN_STATUS(PORTC,PIN2,OUTPUT);
	MDIO_SETPIN_VALUE(PORTC,PIN7,HIGH);
	MDIO_SETPIN_VALUE(PORTC,PIN2,LOW);	
	
	
	MDIO_SETPIN_VALUE(PORTD,PIN0,LOW);
	TIMER0_PWM_SETUP(PWM_NON_INVERT,100);
	TIMER0_INITIALIZE(PWM_PHASE,_1024_PRESCALE);
	
	
	
	while(1)
	{
			TIMER0_PWM_SETUP(PWM_NON_INVERT,100);
			MDIO_TOGGLEPIN_VALUE(PORTC,PIN7);
			MDIO_TOGGLEPIN_VALUE(PORTC,PIN2);
			//TIMER0_delay(5000);
			_delay_ms(5000);
			
			
			
			TIMER0_PWM_SETUP(PWM_NON_INVERT,250);
			MDIO_TOGGLEPIN_VALUE(PORTC,PIN7);
			MDIO_TOGGLEPIN_VALUE(PORTC,PIN2);
			//TIMER0_delay(5000);
			_delay_ms(5000);
			
			TIMER0_PWM_SETUP(PWM_NON_INVERT,50);
			MDIO_TOGGLEPIN_VALUE(PORTC,PIN7);
			MDIO_TOGGLEPIN_VALUE(PORTC,PIN2);
			//TIMER0_delay(5000);
			_delay_ms(5000);

			//_delay_ms(5000);
				}
}

